import type { QuizQuestion } from './types';

export const mathQuizQuestions: QuizQuestion[] = [
  {
    question: 'If a unit trust\'s NAV is $2.00 per unit and it has a front-end load of 5%, what is the offer price for an investor?',
    answers: ['$1.90', '$2.00', '$2.05', '$2.10'],
    correctAnswerIndex: 3,
    rationale: 'The offer price includes the sales charge (front-end load). Calculation: Offer Price = NAV + (NAV * 5%) = $2.00 + ($2.00 * 0.05) = $2.00 + $0.10 = $2.10.',
  },
  {
    question: 'If a fund manager reports a performance of 8% against a benchmark of 4%, with a tracking error of 8%, what is the reported Information Ratio?',
    answers: ['0.25', '0.50', '1.00', '2.00'],
    correctAnswerIndex: 1,
    rationale: 'The Information Ratio is calculated as (Fund Return - Benchmark Return) / Tracking Error. In this case, (8% - 4%) / 8% = 4% / 8% = 0.50. It measures the fund manager\'s ability to generate excess returns relative to a benchmark, adjusted for the volatility of those returns.',
  },
  {
    question: 'A bond has a par value of $1,000 and a coupon rate of 6%. It is currently trading at $920. What is its current yield?',
    answers: ['6.00%', '6.52%', '5.52%', '7.00%'],
    correctAnswerIndex: 1,
    rationale: 'Current Yield is calculated as (Annual Coupon Payment / Current Market Price). The annual coupon is 6% of the $1,000 par value, which is $60. Therefore, the current yield is ($60 / $920) * 100 = 6.52%.',
  },
  {
    question: 'An investor buys 1,000 units of a fund at $2.00 per unit. Over the year, she receives a total of $0.10 in dividends per unit. At the end of the year, the unit price is $2.15. What is her total percentage return on the investment?',
    answers: ['7.5%', '10.0%', '12.5%', '15.0%'],
    correctAnswerIndex: 2,
    rationale: 'Total Return = (Capital Gain + Dividends) / Initial Investment. The capital gain is ($2.15 - $2.00) = $0.15 per unit. The dividend is $0.10 per unit. Total gain per unit is $0.25. The percentage return is ($0.25 / $2.00) * 100 = 12.5%.',
  },
  {
    question: 'A fund achieves a nominal return of 8% for the year. If the inflation rate during the same period was 3%, what is the approximate real rate of return?',
    answers: ['11.0%', '8.0%', '5.0%', '2.6%'],
    correctAnswerIndex: 2,
    rationale: 'The real rate of return adjusts the nominal return for inflation, showing the actual increase in purchasing power. The approximate formula is: Real Return ≈ Nominal Return - Inflation Rate. So, 8% - 3% = 5%.',
  },
  {
    question: 'An investment generates a 10% pre-tax return. If the investor is in a 20% marginal tax bracket, what is the after-tax return?',
    answers: ['12.0%', '10.0%', '8.0%', '2.0%'],
    correctAnswerIndex: 2,
    rationale: 'The after-tax return is calculated by subtracting the amount of tax paid from the pre-tax return. Formula: Pre-Tax Return * (1 - Tax Rate). So, 10% * (1 - 0.20) = 10% * 0.80 = 8%.',
  },
  {
    question: 'A portfolio has a return of 12% and a standard deviation of 15%. If the risk-free rate is 3%, what is its Sharpe Ratio?',
    answers: ['0.80', '0.60', '1.00', '0.40'],
    correctAnswerIndex: 1,
    rationale: 'The Sharpe Ratio measures risk-adjusted return. The formula is: (Portfolio Return - Risk-Free Rate) / Standard Deviation of the portfolio. Calculation: (12% - 3%) / 15% = 9% / 15% = 0.6.',
  },
  {
    question: 'An active fund manager achieves a 10% return, while their benchmark returned 7%. If the fund\'s tracking error is 4%, what is its Information Ratio?',
    answers: ['1.75', '4.25', '0.75', '2.50'],
    correctAnswerIndex: 2,
    rationale: 'The Information Ratio measures a portfolio manager\'s ability to generate excess returns relative to a benchmark, adjusted for the volatility of those returns. Formula: (Portfolio Return - Benchmark Return) / Tracking Error. Calculation: (10% - 7%) / 4% = 3% / 4% = 0.75.',
  },
  {
    question: 'A fund has a return of 15% and a Beta of 1.2. The risk-free rate is 3%. What is the fund\'s Treynor Ratio?',
    answers: ['12.5%', '10.0%', '15.0%', '8.0%'],
    correctAnswerIndex: 1,
    rationale: 'The Treynor Ratio measures the excess return generated per unit of systematic risk (Beta). Formula: (Portfolio Return - Risk-Free Rate) / Beta. Calculation: (15% - 3%) / 1.2 = 12% / 1.2 = 10%.',
  },
  {
    question: 'A fund generated a 14% return. It has a Beta of 1.1, the market return was 10%, and the risk-free rate was 2%. What is the fund\'s Alpha (Jensen\'s Alpha)?',
    answers: ['1.2%', '10.8%', '3.2%', '-1.2%'],
    correctAnswerIndex: 2,
    rationale: 'Alpha = Actual Return - Required Return (from CAPM). First, calculate the required return: 2% + 1.1 * (10% - 2%) = 10.8%. Then, Alpha = 14% - 10.8% = 3.2%. A positive alpha indicates the fund outperformed its expected return.',
  },
  {
    question: 'Using the Rule of 72, approximately how many years would it take for an investment to double in value if it earns a consistent 9% annual return?',
    answers: ['9 years', '7 years', '8 years', '12 years'],
    correctAnswerIndex: 2,
    rationale: 'The Rule of 72 is a quick mental shortcut to estimate the number of years required to double an investment at a given annual rate of return. The formula is: 72 / Interest Rate. Calculation: 72 / 9 = 8 years.',
  },
  {
    question: 'An investor places $10,000 in an account that earns 5% interest compounded annually. What will be the future value of this investment after 3 years?',
    answers: ['$11,500.00', '$10,500.00', '$11,576.25', '$15,000.00'],
    correctAnswerIndex: 2,
    rationale: 'The formula for Future Value (FV) is PV * (1 + r)^n, where PV is present value, r is the interest rate, and n is the number of periods. Calculation: $10,000 * (1 + 0.05)^3 = $10,000 * 1.157625 = $11,576.25.',
  },
  {
    question: 'An individual wants to have $50,000 in 5 years. If they can earn an annual interest rate of 6%, what is the present value they must invest today?',
    answers: ['$47,169.81', '$37,362.91', '$40,000.00', '$53,000.00'],
    correctAnswerIndex: 1,
    rationale: 'The formula for Present Value (PV) is FV / (1 + r)^n, where FV is future value, r is the interest rate, and n is the number of periods. Calculation: $50,000 / (1 + 0.06)^5 = $50,000 / 1.338225 = $37,362.91.',
  },
  {
    question: 'A fund returns +10% in its first year and -5% in its second year. What is the fund\'s geometric mean annual return over the two-year period?',
    answers: ['2.50%', '5.00%', '2.22%', '4.75%'],
    correctAnswerIndex: 2,
    rationale: 'The geometric mean is a more accurate measure of average returns over multiple periods. Formula: [ (1 + R1) * (1 + R2) * ... ]^(1/n) - 1. Calculation: [ (1 + 0.10) * (1 - 0.05) ]^(1/2) - 1 = [ 1.045 ]^(0.5) - 1 ≈ 2.22%.',
  },
  {
    question: 'A unit trust has total assets valued at $100 million and total liabilities of $5 million. If there are 50 million units outstanding, what is the Net Asset Value (NAV) per unit?',
    answers: ['$2.10', '$2.00', '$1.90', '$1.80'],
    correctAnswerIndex: 2,
    rationale: 'The NAV per unit is the fund\'s market value per unit. Formula: (Total Assets - Total Liabilities) / Number of Units Outstanding. Calculation: ($100,000,000 - $5,000,000) / 50,000,000 = $95,000,000 / 50,000,000 = $1.90.',
  },
  {
    question: 'A unit trust has a Net Asset Value (NAV) of $2.00 per unit. If it has a front-end sales charge (load) of 5%, what is the offer price an investor would pay?',
    answers: ['$1.90', '$2.00', '$2.10', '$2.11'],
    correctAnswerIndex: 3,
    rationale: 'For funds with a front-end load, the offer price is the price an investor pays. In Singapore, the sales charge is typically calculated on the offer price itself. Formula: Offer Price = NAV / (1 - Sales Charge %). Calculation: $2.00 / (1 - 0.05) = $2.00 / 0.95 ≈ $2.11.',
  },
  {
    question: 'A fund has an average Net Asset Value (NAV) of $10 million over the year. Its total annual operating expenses were $150,000. What is the fund\'s expense ratio?',
    answers: ['2.0%', '1.0%', '0.15%', '1.5%'],
    correctAnswerIndex: 3,
    rationale: 'The expense ratio shows the annual cost of running the fund as a percentage of its assets. Formula: (Total Annual Expenses / Average NAV) * 100. Calculation: ($150,000 / $10,000,000) * 100 = 1.5%.',
  },
  {
    question: 'An investor redeems 5,000 units of a fund. The bid price is $1.20 per unit, and the fund charges a 1% redemption fee. What are the net cash proceeds the investor will receive?',
    answers: ['$6,060', '$6,000', '$5,940', '$5,400'],
    correctAnswerIndex: 2,
    rationale: 'First, calculate the gross redemption value: 5,000 units * $1.20/unit = $6,000. Then, calculate the redemption fee: $6,000 * 1% = $60. Finally, subtract the fee from the gross value to find the net proceeds: $6,000 - $60 = $5,940.',
  },
  {
    question: 'A manager achieves an 8% return against a benchmark of 4%. If the tracking error (standard deviation of active return) is 8%, what is the Information Ratio?',
    answers: ['0.25', '0.50', '1.00', '1.50'],
    correctAnswerIndex: 1,
    rationale: 'The Information Ratio is calculated as (Active Return) / (Tracking Error). The Active Return is the fund\'s return minus the benchmark\'s return (8% - 4% = 4%). So, the Information Ratio is 4% / 8% = 0.50.',
  },
  {
    question: 'A bond provides $70 of annual income and has a current market price of $1,050. If the investor\'s marginal tax rate (MRT) is 22%, what is the after-tax current yield?',
    answers: ['6.67%', '5.20%', '1.47%', '8.55%'],
    correctAnswerIndex: 1,
    rationale: 'First, calculate the before-tax current yield: (Annual Income / Current Market Price) = ($70 / $1,050) = 6.67%. Then, apply the after-tax formula: Before-Tax Yield * (1 - MRT) = 6.67% * (1 - 0.22) = 5.20%.',
  },
  {
    question: 'You expect to receive a payment of $10,000 one year from now. The payments will grow at a constant rate of 4% per year for a total of 20 years. If the appropriate discount rate (i) is 7%, what is the present value (PV) of this entire stream of payments?',
    answers: ['$144,033', '$200,000', '$100,000', '$135,903'],
    correctAnswerIndex: 0,
    rationale: 'This requires the formula for the present value of a growing annuity: PV = Pmt1 / (i - g) * [1 - ((1+g)/(1+i))^n]. Plugging in the values: PV = $10,000 / (0.07 - 0.04) * [1 - ((1.04)/(1.07))^20] = $144,033.',
  },
  {
    question: 'You are setting up a trust that will make its first payment of $5,000 immediately. The payments will then grow by 2% each year for 15 years. If the discount rate (i) is 5%, what is the present value (PV) of these payments?',
    answers: ['$58,683', '$61,617', '$75,000', '$52,500'],
    correctAnswerIndex: 1,
    rationale: 'This requires the formula for the present value of a growing annuity due, as the first payment is immediate. Formula: PV = [Pmt1 / (i - g) * [1 - ((1+g)/(1+i))^n]] * (1+i). Plugging in the values: PV = [$5,000 / (0.05 - 0.02) * [1 - ((1.02)/(1.05))^15]] * 1.05 = $61,617.',
  },
  {
    question: 'You plan to make your first deposit of $2,000 into a savings plan one year from now. You will increase your deposits by 3% each year for a total of 10 years. The plan earns an annual interest rate of 6%. What is the future value (FV) of your investment at the end of the 10th year?',
    answers: ['$26,361', '$29,793', '$20,000', '$31,580'],
    correctAnswerIndex: 1,
    rationale: 'This uses the formula for the future value of a growing ordinary annuity: FV = Dep1 * [((1+i)^n - (1+g)^n) / (i-g)]. Plugging in the values: FV = $2,000 * [((1.06)^10 - (1.03)^10) / (0.06 - 0.03)] = $29,793.',
  },
  {
    question: 'You plan to deposit $5,000 into an account one year from today. Your deposits will increase by 4% each year for a total of 15 years. The account earns 7% annually. What is the future value of this stream of deposits at the end of the 15th year?',
    answers: ['$125,560', '$159,680', '$75,000', '$170,857'],
    correctAnswerIndex: 1,
    rationale: 'Using the formula for the future value of a growing ordinary annuity: FV = Dep1 * [((1+i)^n - (1+g)^n) / (i-g)]. Calculation: FV = $5,000 * [((1.07)^15 - (1.04)^15) / (0.07 - 0.04)] = $159,680.',
  },
  {
    question: 'A corporate bond has a current market price of $980 and pays an annual coupon (income) of $50. What is the before-tax current yield?',
    answers: ['5.00%', '4.90%', '5.10%', '5.20%'],
    correctAnswerIndex: 2,
    rationale: 'The before-tax current yield is calculated by dividing the annual income from the investment by its current market price. Calculation: $50 / $980 = 5.10%.',
  },
  {
    question: 'A bond\'s before-tax current yield is 8%. Its after-tax current yield is 6%. What is the investor\'s marginal tax rate (MRT)?',
    answers: ['20%', '25%', '30%', '14%'],
    correctAnswerIndex: 2,
    rationale: 'The formula is After-tax yield = Before-tax yield * (1 - MRT). Rearranging to solve for MRT: MRT = 1 - (After-tax yield / Before-tax yield). Calculation: MRT = 1 - (6% / 8%) = 1 - 0.75 = 0.25, or 25%.',
  },
  {
    question: 'An annuity will pay you $20,000 immediately, and the payments will grow by 3% annually for 25 years. If the discount rate is 8%, what is the present value?',
    answers: ['$282,000', '$500,000', '$304,560', '$216,000'],
    correctAnswerIndex: 2,
    rationale: 'This is a growing annuity due. Formula: PV = [Pmt1 / (i - g) * [1 - ((1+g)/(1+i))^n]] * (1+i). Calculation: PV = [$20,000 / (0.08 - 0.03) * [1 - ((1.03)/(1.08))^25]] * 1.08 = $304,560.',
  },
  {
    question: 'A fund generates $120 of annual income. Its current market price is $2,000. For an investor with a 15% marginal tax rate (MRT), what is the after-tax current yield?',
    answers: ['6.0%', '5.1%', '4.9%', '0.9%'],
    correctAnswerIndex: 1,
    rationale: 'First, find the before-tax yield: ($120 / $2,000) = 6.0%. Then, calculate the after-tax yield: 6.0% * (1 - 0.15) = 5.1%.',
  },
  {
    question: 'A retirement plan promises to pay you $50,000 one year from now, with payments growing at 2% per year for 30 years. If the discount rate is 6%, what is the present value of this plan?',
    answers: ['$853,750', '$1,250,000', '$780,550', '$820,330'],
    correctAnswerIndex: 0,
    rationale: 'This uses the formula for the present value of a growing ordinary annuity: PV = Pmt1 / (i - g) * [1 - ((1+g)/(1+i))^n]. Calculation: PV = $50,000 / (0.06 - 0.02) * [1 - ((1.02)/(1.06))^30] = $853,750.',
  },
  {
    question: 'A company has an EBIT Margin of 10%, Asset Turnover of 2, and Financial Leverage of 1.5. Ignoring tax and interest burdens, what is its approximate Return on Equity (ROE)?',
    answers: ['20%', '30%', '15%', '25%'],
    correctAnswerIndex: 1,
    rationale: 'Using the DuPont analysis, ROE is the product of its components. ROE ≈ EBIT Margin * Asset Turnover * Financial Leverage. Calculation: 10% * 2 * 1.5 = 30%.',
  },
  {
    question: 'A bond with a par value of $1,000 pays an annual coupon of $50. What is its Coupon Rate?',
    answers: ['4%', '5%', '6%', '$50'],
    correctAnswerIndex: 1,
    rationale: 'The Coupon Rate is the annual coupon payment expressed as a percentage of the bond\'s par value. Formula: (Annual Coupon / Par Value) * 100. Calculation: ($50 / $1,000) * 100 = 5%.',
  },
  {
    question: 'A bond has a par value of $1,000 and a coupon rate of 8%. It is currently trading for $1,250. What is its Current Yield?',
    answers: ['8.0%', '10.0%', '6.4%', '7.2%'],
    correctAnswerIndex: 2,
    rationale: 'First, find the annual coupon payment: 8% * $1,000 = $80. Then, calculate Current Yield = (Annual Coupon / Bond Price) * 100. Calculation: ($80 / $1,250) * 100 = 6.4%.',
  },
  {
    question: 'An investment gains 20% in year one and then loses 10% in year two. What is the geometric mean return for the two-year period?',
    answers: ['5.00%', '3.92%', '10.0%', '4.50%'],
    correctAnswerIndex: 1,
    rationale: 'To find the geometric mean, convert percentages to multipliers (1.20 for a 20% gain, 0.90 for a 10% loss), multiply them together, take the nth root for n periods, and subtract 1. Calculation: [(1.20 * 0.90)]^(1/2) - 1 = [1.08]^(0.5) - 1 ≈ 3.92%. This is a more accurate measure of compound growth than a simple average.',
  },
  {
    question: 'A bond with a face value of $1,000 makes an annual interest payment of $45. What is its coupon rate?',
    answers: ['4.0%', '4.5%', '5.0%', '$45'],
    correctAnswerIndex: 1,
    rationale: 'The Coupon Rate is the annual interest payment divided by the bond\'s face (or par) value. Calculation: ($45 / $1,000) * 100 = 4.5%.',
  },
  {
    question: 'An investor holds a bond with a face value of $5,000 and a coupon rate of 8%. How much will they receive in annual coupon payments?',
    answers: ['$80', '$400', '$500', '$5,400'],
    correctAnswerIndex: 1,
    rationale: 'The annual coupon payment is calculated by multiplying the face value of the bond by its coupon rate. Calculation: $5,000 * 0.08 = $400.',
  },
  {
    question: 'A bond with a face value of $1,000 has a coupon rate of 7.3%. An investor sells the bond when there are exactly 50 days until the next payment. Using the formula Accrued Coupon = (Face Value * Coupon Rate * Days to Next Payment) / 365, what is the accrued coupon?',
    answers: ['$10', '$20', '$36.50', '$7.30'],
    correctAnswerIndex: 0,
    rationale: 'Using the provided formula: Accrued Coupon = ($1,000 * 0.073 * 50) / 365. This simplifies to ($73 * 50) / 365 = $3650 / 365 = $10.',
  },
  {
    question: 'A corporate bond with a face value of $10,000 has an 8% coupon rate. It is sold 45 days before its next payment date. Assuming a 360-day year is used for calculation per the provided formula, what is the accrued interest owed to the seller?',
    answers: ['$800.00', '$200.00', '$100.00', '$45.00'],
    correctAnswerIndex: 2,
    rationale: 'Using the formula Accrued Coupon = (Face Value * Coupon Rate * Days to Next Payment) / Days in Year. Calculation: ($10,000 * 0.08 * 45) / 360 = ($800 * 45) / 360 = $800 / 8 = $100.',
  },
  {
    question: 'A bond paying semi-annual coupons has a Macaulay Duration of 8 years and a YTM of 4%. What is its Modified Duration?',
    answers: ['8.16 years', '8.00 years', '7.84 years', '7.69 years'],
    correctAnswerIndex: 2,
    rationale: 'The formula for Modified Duration for a semi-annual bond is: Macaulay Duration / (1 + YTM/2). Calculation: 8 / (1 + 0.04/2) = 8 / 1.02 ≈ 7.84 years.',
  },
  {
    question: 'A bond has a Modified Duration of 9 years. If market interest rates increase by 1% (dy = 0.01), what is the approximate percentage change in the bond\'s price?',
    answers: ['+9%', '-9%', '+1%', '-1%'],
    correctAnswerIndex: 1,
    rationale: 'The formula for approximate price change is: -Modified Duration * Change in Interest Rates (in decimal). Calculation: -9 * 0.01 = -0.09, which is a -9% change.',
  },
  {
    question: 'A bond\'s price fell by approximately 6% when interest rates rose by 1.5%. What is the bond\'s approximate Modified Duration?',
    answers: ['4 years', '6 years', '9 years', '1.5 years'],
    correctAnswerIndex: 0,
    rationale: 'The formula can be rearranged to solve for Modified Duration: D* ≈ -(% Change in Price / Change in Rates). Calculation: -(-6% / 1.5%) = 4. The bond has a modified duration of approximately 4 years.',
  },
  {
    question: 'A fund has an actual return of 12%, a Beta of 0.9, a market return of 11%, and a risk-free rate of 3%. What is its Alpha?',
    answers: ['1.8%', '10.2%', '-1.8%', '2.2%'],
    correctAnswerIndex: 0,
    rationale: 'First, calculate the expected return using CAPM: 3% + 0.9 * (11% - 3%) = 10.2%. Then, calculate Alpha: Actual Return - Expected Return = 12% - 10.2% = 1.8%.',
  },
  {
    question: 'A fund returns 8%. It has a Beta of 1.5, the market returned 6%, and the risk-free rate is 1%. What is the fund\'s Alpha?',
    answers: ['-0.5%', '8.5%', '0.5%', '2.5%'],
    correctAnswerIndex: 0,
    rationale: 'First, calculate the expected return using CAPM: 1% + 1.5 * (6% - 1%) = 8.5%. Then, calculate Alpha: Actual Return - Expected Return = 8% - 8.5% = -0.5%. A negative alpha indicates underperformance.',
  },
  {
    question: 'A fund has a Beta of 1.0 and returned 15%. If the market return was 13% and the risk-free rate was 3%, what is the fund\'s Alpha?',
    answers: ['2.0%', '13.0%', '-2.0%', '1.0%'],
    correctAnswerIndex: 0,
    rationale: 'First, calculate the expected return using CAPM: 3% + 1.0 * (13% - 3%) = 13%. Then, calculate Alpha: Actual Return - Expected Return = 15% - 13% = 2.0%.',
  },
  {
    question: 'An investment returned 5%. It has a Beta of 0.8, the market return was 7%, and the risk-free rate was 4%. What is its Alpha?',
    answers: ['-1.4%', '6.4%', '1.4%', '-2.4%'],
    correctAnswerIndex: 0,
    rationale: 'First, calculate the expected return using CAPM: 4% + 0.8 * (7% - 4%) = 6.4%. Then, calculate Alpha: Actual Return - Expected Return = 5% - 6.4% = -1.4%.',
  },
  {
    question: 'A portfolio generated a 20% return. It has a Beta of 1.3, while the market returned 15% and the risk-free rate was 4%. What is the portfolio\'s Alpha?',
    answers: ['1.7%', '18.3%', '-1.7%', '2.7%'],
    correctAnswerIndex: 0,
    rationale: 'First, calculate the expected return using CAPM: 4% + 1.3 * (15% - 4%) = 18.3%. Then, calculate Alpha: Actual Return - Expected Return = 20% - 18.3% = 1.7%.',
  },
  {
    question: 'A portfolio gains 15% in the first year, loses 5% in the second year, and gains 8% in the third year. What is its geometric mean annual return?',
    answers: ['6.00%', '5.67%', '5.89%', '7.50%'],
    correctAnswerIndex: 1,
    rationale: 'The geometric mean return is calculated by multiplying the returns for each period (as multipliers), taking the nth root where n is the number of periods, and subtracting 1. Calculation: [(1.15 * 0.95 * 1.08)]^(1/3) - 1 ≈ 5.67%.',
  },
  {
    question: 'An investment doubles in value over 5 years. What is the approximate geometric mean annual return?',
    answers: ['20.0%', '15.5%', '14.87%', '12.5%'],
    correctAnswerIndex: 2,
    rationale: 'If an investment doubles, the total return multiplier is 2. To find the geometric mean annual return over 5 years, you calculate the 5th root of 2 and subtract 1. Calculation: (2)^(1/5) - 1 ≈ 14.87%.',
  },
  {
    question: 'A fund returns +50% in year one and -50% in year two. What is the geometric mean annual return?',
    answers: ['0%', '-10.5%', '-13.4%', '-25.0%'],
    correctAnswerIndex: 2,
    rationale: 'A simple average would misleadingly suggest a 0% return. The geometric mean correctly shows the loss. Calculation: [(1.50 * 0.50)]^(1/2) - 1 = [0.75]^(0.5) - 1 ≈ -13.4%. This demonstrates that a 50% loss requires a 100% gain to break even, not just a 50% gain.',
  },
  {
    question: 'A fund has an expected return of 10% and a standard deviation of 5%. According to the 68% confidence level, what is the range of expected returns?',
    answers: ['5% to 15%', '10% to 20%', '0% to 20%', '5% to 10%'],
    correctAnswerIndex: 0,
    rationale: 'The 68-95-99.7 rule states that approximately 68% of returns will fall within one standard deviation of the mean. The range is calculated as Mean ± 1 SD, which is 10% ± 5%, resulting in a range of 5% to 15%.',
  },
  {
    question: 'Using the same fund (10% return, 5% SD), what is the range of returns at a 95% confidence level?',
    answers: ['5% to 15%', '0% to 20%', '-5% to 25%', '10% to 20%'],
    correctAnswerIndex: 1,
    rationale: 'At a 95% confidence level, returns are expected to be within two standard deviations of the mean. The range is calculated as Mean ± 2 SD, which is 10% ± (2 * 5%) or 10% ± 10%, resulting in a range of 0% to 20%.',
  },
  {
    question: 'If a stock has an average return of 5% and an SD of 10%, what is the "worst-case" return at a 95% confidence level?',
    answers: ['5%', '-5%', '-10%', '-15%'],
    correctAnswerIndex: 3,
    rationale: 'The 95% confidence interval is Mean ± 2 SD. The \'worst-case\' return is the lower bound of this range. Calculation: 5% - (2 * 10%) = 5% - 20% = -15%.',
  },
];
