import type { QuizQuestion } from './types';

export const seedQuizQuestions: QuizQuestion[] = [
  {
    question: 'Which of the following best describes a unit trust?',
    answers: [
      'A high-risk investment product that guarantees returns.',
      'A collective investment scheme where investors pool their money to invest in a diversified portfolio.',
      'A type of savings account with a fixed interest rate.',
      'A direct investment in a single company\'s stock.',
    ],
    correctAnswerIndex: 1,
    rationale:
      'A unit trust is a collective investment scheme where funds from many investors are pooled to purchase a diversified portfolio of assets, spreading risk.',
  },
  {
    question: 'What is the primary role of a fund manager in a unit trust?',
    answers: [
      'To provide legal advice to the trust.',
      'To manage the investment portfolio of the fund in line with its objectives.',
      'To handle the administrative and custodial tasks.',
      'To sell the unit trusts to investors.',
    ],
    correctAnswerIndex: 1,
    rationale:
      'A fund manager\'s main responsibility is to manage the fund\'s investment portfolio to achieve its stated objectives.',
  },
  {
    question: 'An investor who is risk-averse and has a small amount of capital would find which of the following most suitable?',
    answers: ['Derivatives', 'A single, high-growth stock', 'A unit trust', 'A hedge fund'],
    correctAnswerIndex: 2,
    rationale:
      'Unit trusts offer diversification, which lowers risk, making them suitable for risk-averse investors with limited capital.',
  },
  {
    question: 'What does NAV stand for in the context of a unit trust?',
    answers: ['Net Asset Value', 'New Asset Valuation', 'Nominal Asset Value', 'Net-Associated Value'],
    correctAnswerIndex: 0,
    rationale: 'NAV stands for Net Asset Value, which represents the per-unit market value of the fund.',
  },
  {
    question: 'If a unit trust\'s NAV is $2.00 per unit and it has a front-end load of 5%, what is the offer price for an investor?',
    answers: ['$1.90', '$2.00', '$2.05', '$2.10'],
    correctAnswerIndex: 3,
    rationale: 'The offer price is NAV + (NAV * front-end load). $2.00 + ($2.00 * 0.05) = $2.10.',
  },
  {
    question: 'Which of the following is NOT a typical risk associated with bond funds?',
    answers: ['Interest rate risk', 'Credit risk', 'Liquidity risk', 'unlimited upside potential'],
    correctAnswerIndex: 3,
    rationale: 'Bonds offer fixed-income, so their upside potential is limited, which is a characteristic, not a risk.',
  },
  {
    question: 'A "growth" investment strategy primarily focuses on:',
    answers: [
      'Investing in companies that are undervalued.',
      'Investing in companies with high potential for future earnings growth.',
      'Investing in government bonds for stable income.',
      'Investing in a mix of assets to minimize risk.',
    ],
    correctAnswerIndex: 1,
    rationale: 'Growth investing targets companies expected to have high earnings growth in the future, aiming for capital appreciation.',
  },
  {
    question: 'What is a feeder fund?',
    answers: [
      'A fund that invests directly in a variety of securities.',
      'A fund that invests in a master fund which in turn holds the investments.',
      'A fund that only invests in commodities.',
      'A fund that is managed by multiple fund managers.',
    ],
    correctAnswerIndex: 1,
    rationale: 'A feeder fund pools capital and "feeds" it into a central master fund, which handles the investments.',
  },
  {
    question: 'Which of the following is a key feature of Real Estate Investment Trusts (REITs)?',
    answers: [
      'They are not traded on stock exchanges.',
      'They primarily invest in technology stocks.',
      'They allow investors to invest in a portfolio of real estate assets.',
      'They are exempt from all market risks.',
    ],
    correctAnswerIndex: 2,
    rationale: 'REITs are investment vehicles that allow individuals to invest in a diversified portfolio of real estate properties.',
  },
  {
    question: 'What is dollar-cost averaging?',
    answers: [
      'An investment strategy where you try to time the market to buy low and sell high.',
      'Investing a fixed amount of money at regular intervals, regardless of market fluctuations.',
      'A method for calculating the average cost of all your investments.',
      'A strategy to only invest in US dollar-denominated assets.',
    ],
    correctAnswerIndex: 1,
    rationale: 'Dollar-cost averaging involves investing a fixed sum regularly, which can reduce the impact of market volatility.',
  },
  {
    question: 'What is the primary purpose of a "prospectus" for a unit trust?',
    answers: [
      'To provide a summary of the fund\'s past performance.',
      'To serve as a marketing brochure to attract investors.',
      'To provide detailed information about the fund, including its investment objectives, strategies, risks, and fees.',
      'To list the names of all the current unitholders.',
    ],
    correctAnswerIndex: 2,
    rationale: 'A prospectus is a legal document that provides comprehensive details about an investment offering to help investors make informed decisions.',
  },
  {
    question: 'An investor seeking a regular income stream would be most interested in which type of fund?',
    answers: ['A growth fund', 'An aggressive growth fund', 'An income fund', 'A sector fund focused on technology.'],
    correctAnswerIndex: 2,
    rationale: 'Income funds are designed to provide a steady stream of income by investing in dividend-paying stocks and bonds.',
  },
  {
    question: 'In which of the following situations would a currency swap be most useful?',
    answers: [
      'When an investor wants to exchange one stock for another.',
      'When two parties want to exchange interest rate payments on a notional principal amount.',
      'When two companies in different countries with borrowings in their local currencies want to hedge against foreign exchange risk.',
      'When a company wants to convert its debt into equity.',
    ],
    correctAnswerIndex: 2,
    rationale: 'Currency swaps are used to hedge against exchange rate fluctuations by exchanging principal and/or interest payments in different currencies.',
  },
  {
    question: 'What does "beta" measure?',
    answers: [
      'The total risk of a portfolio.',
      'The volatility of a security or a portfolio in comparison to the market as a whole.',
      'The alpha or excess return of a fund manager.',
      'The credit rating of a bond.',
    ],
    correctAnswerIndex: 1,
    rationale: 'Beta is a measure of systematic risk, indicating how much an asset\'s price moves in relation to the overall market.',
  },
  {
    question: 'A fund with a beta of 1.5 would be expected to:',
    answers: [
      'Be 50% less volatile than the market.',
      'Move in the opposite direction of the market.',
      'Be 50% more volatile than the market.',
      'Perfectly track the market\'s performance.',
    ],
    correctAnswerIndex: 2,
    rationale: 'A beta greater than 1 indicates that the asset is more volatile than the market. A beta of 1.5 suggests it is 50% more volatile.',
  },
  {
    question: 'Which of the following is considered a "money market" instrument?',
    answers: ['A 30-year government bond', 'A common stock', 'A commercial paper', 'A real estate property'],
    correctAnswerIndex: 2,
    rationale: 'Money market instruments are short-term, highly liquid debt securities. Commercial paper is a common example.',
  },
  {
    question: 'What is "diversification"?',
    answers: [
      'A strategy of concentrating investments in a single asset class.',
      'A risk management strategy that mixes a wide variety of investments within a portfolio.',
      'A method of timing the market to maximize returns.',
      'A way to guarantee that an investment will not lose money.',
    ],
    correctAnswerIndex: 1,
    rationale: 'Diversification is a core risk management principle that involves spreading investments across various assets to reduce the impact of any single asset\'s performance.',
  },
  {
    question: 'For a "value" investor, which of the following is the most important factor?',
    answers: [
      'The company\'s recent stock price performance.',
      'The potential for rapid future growth.',
      'Whether the company\'s stock is trading at a price below its intrinsic value.',
      'The level of media attention the company is receiving.',
    ],
    correctAnswerIndex: 2,
    rationale: 'Value investing focuses on finding and investing in stocks that appear to be trading for less than their intrinsic or book value.',
  },
  {
    question: 'What is the main risk associated with a "junk bond" fund?',
    answers: ['Interest rate risk', 'Inflation risk', 'Credit or default risk', 'Liquidity risk'],
    correctAnswerIndex: 2,
    rationale: 'Junk bonds are issued by companies with a higher risk of default, so the main risk is credit risk—the risk that the issuer will not be able to make its payments.',
  },
  {
    question: 'Which of the following best describes an Exchange-Traded Fund (ETF)?',
    answers: [
      'A mutual fund that is not traded on an exchange.',
      'A fund that can be bought and sold throughout the day on an exchange, like a stock.',
      'A fund that only invests in government-issued securities.',
      'A fund that is actively managed and aims to beat the market.',
    ],
    correctAnswerIndex: 1,
    rationale: 'ETFs are traded on stock exchanges, similar to stocks, allowing for intraday buying and selling.',
  },
  {
    question: '"Mark-to-market" is a method of:',
    answers: [
      'Valuing assets based on their original purchase price.',
      'Valuing assets based on their current market price.',
      'A marketing strategy for financial products.',
      'Calculating the historical average return of a fund.',
    ],
    correctAnswerIndex: 1,
    rationale: 'Mark-to-market accounting values assets at their current market price to provide a realistic assessment of their value.',
  },
  {
    question: 'What is a "Collateralized Debt Obligation" (CDO)?',
    answers: [
      'A type of savings bond issued by the government.',
      'A simple investment vehicle with very low risk.',
      'A complex structured finance product that is backed by a pool of loans and other assets.',
      'A type of insurance policy for investments.',
    ],
    correctAnswerIndex: 2,
    rationale: 'CDOs are complex financial instruments that pool together cash flow-generating assets and repackage them into tranches with different risk profiles.',
  },
  {
    question: 'An annuity is primarily used for:',
    answers: [
      'Short-term, high-risk speculation.',
      'Providing a lump-sum payment upon death.',
      'Generating a regular stream of income, typically during retirement.',
      'Investing in emerging market stocks.',
    ],
    correctAnswerIndex: 2,
    rationale: 'Annuities are financial products that provide a steady stream of income, making them a popular tool for retirement planning.',
  },
  {
    question: 'In the context of derivatives, what is the "initial margin"?',
    answers: [
      'The final profit or loss on a trade.',
      'A fee paid to the broker for executing the trade.',
      'The commission charged by the clearinghouse.',
      'The collateral required to open and maintain a position.',
    ],
    correctAnswerIndex: 3,
    rationale: 'Initial margin is the good-faith deposit or collateral required to initiate and hold a leveraged position in derivatives.',
  },
  {
    question: 'If inflation is expected to rise, an investor holding long-duration bonds should consider:',
    answers: [
      'Increasing their holdings of long-duration bonds.',
      'Selling their long-duration bonds.',
      'Buying more long-duration bonds on margin.',
      'Ignoring the inflation forecast as it does not affect bond prices.',
    ],
    correctAnswerIndex: 1,
    rationale: 'Rising inflation often leads to rising interest rates, which causes the price of existing bonds (especially long-duration ones) to fall.',
  },
  {
    question: 'What is the role of a "custodian" in a collective investment scheme?',
    answers: [
      'To make investment decisions for the fund.',
      'To hold the fund\'s assets for safekeeping.',
      'To market the fund to potential investors.',
      'To audit the fund\'s financial statements.',
    ],
    correctAnswerIndex: 1,
    rationale: 'A custodian is a financial institution responsible for holding and safeguarding the securities and assets of a fund.',
  },
  {
    question: 'A "balanced fund" typically invests in:',
    answers: ['Only equities.', 'Only bonds.', 'A mix of equities and bonds.', 'Only money market instruments.'],
    correctAnswerIndex: 2,
    rationale: 'Balanced funds aim to provide a balance of growth and income by investing in a mix of stocks (equities) and bonds.',
  },
  {
    question: 'What is "alpha" in the context of fund performance?',
    answers: [
      'A measure of a fund\'s volatility.',
      'The return generated by the market.',
      'The excess return of a fund relative to its benchmark, after adjusting for risk.',
      'The expense ratio of the fund.',
    ],
    correctAnswerIndex: 2,
    rationale: 'Alpha measures a portfolio manager\'s ability to generate returns above a benchmark, adjusted for the risk taken.',
  },
  {
    question: 'Which of the following is a feature of a "credit-linked note"?',
    answers: [
      'It is a risk-free investment.',
      'The return is linked to a credit event, such as a default, of a reference entity.',
      'It is a type of government bond.',
      'It is guaranteed by a third-party insurance provider.',
    ],
    correctAnswerIndex: 1,
    rationale: 'A credit-linked note is a security whose return is dependent on a specific credit event, such as the default of a particular company.',
  },
  {
    question: 'The "expense ratio" of a fund has what effect on its performance?',
    answers: [
      'A high expense ratio generally improves fund performance.',
      'A high expense ratio negatively impacts fund performance.',
      'The expense ratio has no impact on fund performance.',
      'The expense ratio is only relevant for bond funds.',
    ],
    correctAnswerIndex: 1,
    rationale: 'The expense ratio represents the annual costs of operating the fund, which are deducted from the fund\'s assets, thereby reducing returns for investors.',
  },
  {
    question: 'A "debt-to-equity swap" involves:',
    answers: [
      'Exchanging one type of debt for another.',
      'Exchanging debt for equity in a company.',
      'Exchanging equity for debt.',
      'Swapping currencies between two parties.',
    ],
    correctAnswerIndex: 1,
    rationale: 'This is a recapitalization strategy where a company\'s debt is exchanged for a portion of its equity, often to relieve financial distress.',
  },
  {
    question: 'What is the primary risk associated with "distressed debt" investing?',
    answers: [
      'The company in question may not recover, leading to a total loss of investment.',
      'The debt may be too liquid.',
      'The interest rates may fall.',
      'The company\'s credit rating may improve too quickly.',
    ],
    correctAnswerIndex: 0,
    rationale: 'Distressed debt investing is high-risk because it involves buying the debt of companies in financial trouble. If the company fails, the investment can be lost entirely.',
  },
  {
    question: 'As an investment horizon lengthens, what is a likely benefit?',
    answers: [
      'The standard deviation of average annual returns tends to decrease.',
      'Liquidity of the underlying assets always improves.',
      'The risk of losing the entire principal increases.',
      'The potential for high short-term gains increases.',
    ],
    correctAnswerIndex: 0,
    rationale: 'Longer investment horizons allow time to recover from market downturns, generally leading to less volatility (lower standard deviation) in average annual returns.',
  },
  {
    question: 'For an investor focused on capital preservation, which instrument is most suitable?',
    answers: ['Derivatives', 'Growth stocks', 'Money market funds', 'Structured products'],
    correctAnswerIndex: 2,
    rationale: 'Money market funds are highly liquid and low-risk, making them suitable for investors whose primary goal is to preserve capital.',
  },
  {
    question: 'A "regular investment plan" is another term for:',
    answers: ['Value investing', 'Growth investing', 'Dollar-cost averaging', 'Market timing'],
    correctAnswerIndex: 2,
    rationale: 'A regular investment plan is synonymous with dollar-cost averaging, where a fixed amount is invested at regular intervals.',
  },
  {
    question: 'The duration of the underlying securities in a fixed income fund is a key measure of its:',
    answers: ['Credit quality', 'Sensitivity to interest rate changes', 'Yield to maturity', 'Liquidity'],
    correctAnswerIndex: 1,
    rationale: 'Duration measures how much a bond\'s price is likely to change in response to a 1% change in interest rates.',
  },
  {
    question: 'Which market is a specialty market often dominated by hedge funds?',
    answers: ['Government bonds', 'Blue-chip stocks', 'Distressed debt', 'Index funds'],
    correctAnswerIndex: 2,
    rationale: 'Distressed debt is a niche and complex market that requires specialized expertise, making it a common area for hedge funds.',
  },
  {
    question: 'If interest rates are rising, what is the likely impact on a long-duration income fund?',
    answers: ['Its value will increase.', 'Its value will decrease.', 'Its value will remain unchanged.', 'Its credit risk will decrease.'],
    correctAnswerIndex: 1,
    rationale: 'When interest rates rise, newly issued bonds have higher yields, making existing bonds with lower yields (especially long-duration ones) less attractive and causing their prices to fall.',
  },
  {
    question: 'What is a significant risk for most common Exchange Traded Funds (ETFs)?',
    answers: ['Counterparty risk', 'Market risk', 'Default risk of the fund itself', 'Lack of diversification'],
    correctAnswerIndex: 1,
    rationale: 'Because ETFs track market indexes, they are subject to the same market risks as the indexes they follow. If the market goes down, the ETF value will go down.',
  },
  {
    question: 'Using the Capital Asset Pricing Model (CAPM), what is the formula for expected return?',
    answers: ['Rf + Beta * (Rm - Rf)', 'Rf - Beta * (Rm - Rf)', 'Alpha + Rf + Beta * (Rm - Rf)', '(Rm - Rf) / Beta'],
    correctAnswerIndex: 0,
    rationale: 'The CAPM formula calculates the expected return of an asset based on the risk-free rate (Rf), the asset\'s beta, and the expected market return (Rm).',
  },
  {
    question: 'What is a "sovereign bond"?',
    answers: [
      'A bond issued by a corporation.',
      'A bond issued by a national government.',
      'A bond that is secured by a mortgage.',
      'A bond with a very high risk of default.',
    ],
    correctAnswerIndex: 1,
    rationale: 'Sovereign bonds are debt securities issued by a national government to finance its spending.',
  },
  {
    question: 'A "debt-for-debt swap" typically involves:',
    answers: [
      'Exchanging debt for shares in a company.',
      'A company buying back its own debt at a discount.',
      'Exchanging existing debt for new debt with different terms (e.g., maturity or interest rate).',
      'A mechanism to eliminate all debt from a company\'s balance sheet.',
    ],
    correctAnswerIndex: 2,
    rationale: 'In a debt-for-debt swap, a company exchanges its existing debt instruments for new ones with different conditions, often to improve its financial standing.',
  },
  {
    question: 'The "Sharpe Ratio" is used to measure:',
    answers: [
      'The total return of a fund.',
      'The risk-adjusted return of an investment.',
      'The level of diversification in a portfolio.',
      'The amount of leverage used by a fund.',
    ],
    correctAnswerIndex: 1,
    rationale: 'The Sharpe Ratio measures the performance of an investment compared to a risk-free asset, after adjusting for its risk (volatility).',
  },
  {
    question: 'What is a primary characteristic of a "closed-end fund"?',
    answers: [
      'It issues and redeems shares on a continuous basis.',
      'The number of shares is fixed, and it trades on an exchange like a stock.',
      'It only invests in government securities.',
      'It is not professionally managed.',
    ],
    correctAnswerIndex: 1,
    rationale: 'A closed-end fund has a fixed number of shares that are traded on a stock exchange, with prices determined by market supply and demand.',
  },
  {
    question: '"Systematic risk" is also known as:',
    answers: ['Unsystematic risk', 'Diversifiable risk', 'Market risk', 'Specific risk'],
    correctAnswerIndex: 2,
    rationale: 'Systematic risk, or market risk, is inherent to the entire market and cannot be eliminated through diversification.',
  },
  {
    question: 'Which of the following is an example of "unsystematic risk"?',
    answers: ['A global recession', 'A sudden increase in interest rates', 'A labor strike at a single company', 'A change in the inflation rate'],
    correctAnswerIndex: 2,
    rationale: 'Unsystematic risk is specific to a company or industry and can be reduced through diversification. A labor strike at one company is a specific event.',
  },
  {
    question: 'A "fund of funds" is a portfolio that invests in:',
    answers: ['Direct real estate', 'A variety of other funds', 'Physical commodities', 'A single company\'s stock'],
    correctAnswerIndex: 1,
    rationale: 'A fund of funds is a mutual fund that invests in other mutual funds rather than individual securities.',
  },
  {
    question: 'What is the main objective of an "index fund"?',
    answers: [
      'To actively select stocks to outperform the market.',
      'To replicate the performance of a specific market index.',
      'To invest in high-risk, high-return assets.',
      'To provide a fixed income stream to investors.',
    ],
    correctAnswerIndex: 1,
    rationale: 'Index funds are passively managed and aim to match the performance of a particular market index, such as the S&P 500.',
  },
  {
    question: 'An investment with high liquidity means:',
    answers: [
      'It is a long-term investment.',
      'It is difficult to sell.',
      'It cannot be converted to cash easily.',
      'It can be quickly converted to cash without significantly affecting its market price.',
    ],
    correctAnswerIndex: 3,
    rationale: 'Liquidity refers to the ease with which an asset can be bought or sold in the market without causing a significant change in its price.',
  },
  {
    question: 'What is "short selling"?',
    answers: [
      'Selling an asset that you own.',
      'A strategy that profits if the price of an asset falls.',
      'A strategy that profits if the price of an asset rises.',
      'Holding an investment for a very short period.',
    ],
    correctAnswerIndex: 1,
    rationale: 'Short selling involves selling a borrowed security in the hope that its price will decline, allowing the seller to buy it back at a lower price for a profit.',
  },
  {
    question: 'Which of the following is a characteristic of a hedge fund?',
    answers: [
      'They are typically available to all retail investors.',
      'They are highly regulated and transparent.',
      'They often use leverage and invest in a wide range of assets.',
      'They guarantee positive returns regardless of market conditions.',
    ],
    correctAnswerIndex: 2,
    rationale: 'Hedge funds are known for using advanced and often aggressive strategies, including leverage, to generate high returns for their accredited investors.',
  },
  {
    question: 'An investor expecting a market downturn might engage in which of the following strategies?',
    answers: [
      'Buying call options',
      'Increasing their holdings in high-growth stocks',
      'Short selling or buying put options',
      'Investing in a leveraged ETF.',
    ],
    correctAnswerIndex: 2,
    rationale: 'Short selling and buying put options are bearish strategies that profit from a decline in an asset\'s price, making them suitable for market downturns.',
  },
  {
    question: 'The expense ratio of a unit trust represents the:',
    answers: [
      'The fund\'s historical performance.',
      'The total return an investor can expect.',
      'The annual cost of running the fund, expressed as a percentage of the fund\'s assets.',
      'The commission paid to the broker for buying the units.',
    ],
    correctAnswerIndex: 2,
    rationale: 'The expense ratio covers the fund\'s operating costs, such as management fees and administrative expenses, and is expressed as a percentage of the fund\'s average assets.',
  },
];
